name: Check pull request

on: push

jobs:
   build:
     name: Check pull request
     runs-on: ubuntu-latest
     steps:
     - name: Install npm dependencies
       run: |
          ls -la
          npm install