name: Check pull request

on: push

jobs:
   build:
     name: Check pull request
     runs-on: ubuntu-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Install npm dependencies
         run: |
           ls -la
           npm install