name: Check pull request

on: push

jobs:
   build:
     name: Check pull request
     runs-on: ubuntu-20.04
     steps:
     - name: Install npm dependencies
       run: |
       ls -la
       npm install