name: Create Windows/Linux build artifacts

on: push

jobs:
   build:
     name: Check pull request
     runs-on: ubuntu-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Add dependencies
         run: |
          sudo apt install wine-stable
          sudo apt install mono-complete
       - name: Create builds
         run: |
          sudo npm install -g electron-installer-debian
          npm install
          npm run build
       - name: Create installers
          run: |
           npm run setup:deb
           npm run setup
       - name: Create zips
         run: |
          npm run zip
       - name: Archive production artifacts
         uses: actions/upload-artifact@v2
         with:
          name: LinuxWindowsArtifacts
          path: |
            dist/zips
            dist/installers
           