name: Create Windows build artifacts

on:
  workflow_run:
    workflows: ["Create Linux build artifacts (amd64)"]
    types: 
      - completed

jobs:
   build:
     name: Create Windows artifact
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Create build
         run: |
          npm install
          npm run build:win64
          npm run build:win32
       - name: Create installers
         run: |
           npm run setup:win64
           npm run build:win32
       - name: Create zips
         run: |
          npm run zip:win64
          npm run zip:win32
       - name: Archive production artifacts
         uses: actions/upload-artifact@v2
         with:
          name: WindowsArtifacts
          path: |
            dist/zips
            dist/installers/win64/*.exe
            dist/installers/win32/*.exe
           