name: Create Windows/Linux build artifacts

on: push

jobs:
   build:
     name: Check pull request
     runs-on: ubuntu-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Create builds
         run: |
          sudo npm install -g electron-installer-debian
          sudo npm install
          sudo npm run build
       - name: List content
         run: |
           cd dist/
           ls -la
           